[package]
name = "rust-rbe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bn254 = "0.4.0"
ark-ec = "0.4"
ark-ff = "0.4"
ark-std = "0.4"
ark_serialize = "0.4"