[profile.default]
src = "contracts"
out = "contracts/out"
libs = ["contracts/lib"]
solc = "0.8.16"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
